# Generated by Django 5.2 on 2025-06-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='person',
            new_name='client',
        ),
    ]
